PermitRootLogin prohibit-password
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
StrictModes yes
AllowTcpForwarding yes
GatewayPorts no
X11Forwarding no
PermitTunnel no
